### ISSUE TITLE
MAL 40148 wrong mapping

### ISSUE THREAD

**Issue by Oydjayvagr** [Fribb/anime-lists#1]
Hello there, 

the MAL id 40148 is mapped with TheTVDB 77864, but it's wrong.
The correct mapping for the TheTVDB would be 372084 .

The two shows share a very similar name.

The wrong one:
![WRONG](https://user-images.githubusercontent.com/46596694/75286632-194b1880-5819-11ea-89e4-d844665e779f.JPG)

The correct one:
![CORRECT](https://user-images.githubusercontent.com/46596694/75286637-1a7c4580-5819-11ea-806e-165f805cdfbb.JPG)

I take this opportunity to thank you for your hard work!

**Comment by Fribb** [comment]
I updated the corrections list and integrated it in the full mapping. The full list will be updated in a few hours
