### ISSUE TITLE
External ID exist but isnt in list

### ISSUE THREAD

**Issue by kiam001** [Fribb/anime-lists#18]
tmdb does not update some

sampel: https://www.themoviedb.org/tv/46414-kanokon/edit?active_nav_item=external_ids
but arm-server only give this

{
  "anidb": 5575,
  "anilist": 3503,
  "anime-planet": "kanokon",
  "anisearch": 4605,
  "imdb": null,
  "kitsu": 3056,
  "livechart": 3687,
  "notify-moe": "c59w5Fimg",
  "themoviedb": null,
  "thetvdb": 81830,
  "myanimelist": 3503
}

**Comment by Fribb** [comment]
Okay, I debugged this and found the reason.

The generator that creates the merged list iterates over the Anime-Offline-Database which has the following item for the AnimeDB ID 5575

```
  {
    "livechart_id": 3687,
    "anime-planet_id": "kanokon",
    "anisearch_id": 4605,
    "anidb_id": 5575,
    "kitsu_id": 3056,
    "mal_id": 3503,
    "type": "TV",
    "notify.moe_id": "c59w5Fimg",
    "
```

This has the Type "TV", at the time of writing the generator, TheMovieDB didn't had support for TV Shows hence why I specifically restricted the TMDB request to the Type "MOVIE" only.

That is why the `themoviedb` is null.

I will have to see what I can do about this. But this would have to be fixed on the generator side.

**Comment by Fribb** [comment]
Closing this issue since the problem and fix has to happen in the generator
