### ISSUE TITLE
More Issues

### ISSUE THREAD

**Issue by meisnate12** [Fribb/anime-lists#8]
mad_id: [937](https://myanimelist.net/anime/937)
is not thetvdb_id: [245451](https://thetvdb.com/?tab=series&id=245451)
the thetvdb_id should be removed
has no themoviedb_id should be: [45295](https://www.themoviedb.org/movie/45295)

mad_id: [10689](https://myanimelist.net/anime/10689)
has no themoviedb_id should be: [271924](https://www.themoviedb.org/movie/271924)

mad_id: [10693](https://myanimelist.net/anime/10693)
has no themoviedb_id should be: [265805](https://www.themoviedb.org/movie/265805)

mal_id: [9163](https://myanimelist.net/anime/9163)
is not themoviedb_id: [295830](https://www.themoviedb.org/movie/295830)
the themoviedb_id should be: [663241](https://www.themoviedb.org/movie/663241)

mal_id: [34227](https://myanimelist.net/anime/34227)
is not themoviedb_id: [321612](https://www.themoviedb.org/movie/321612)
I could not find the correct one

mad_id: [18759](https://myanimelist.net/anime/18759)
is not themoviedb_id: [268531](https://www.themoviedb.org/movie/268531)
I could not find the correct one

mad_id: [35379](https://myanimelist.net/anime/35379)
is not themoviedb_id: [18823](https://www.themoviedb.org/movie/18823)
the themoviedb_id should be: [266630](https://www.themoviedb.org/movie/266630)

mad_id: [39938](https://myanimelist.net/anime/39938)
is not themoviedb_id: [23742](https://www.themoviedb.org/movie/23742)
the themoviedb_id should be: [642538](https://www.themoviedb.org/movie/642538)

mad_id: [499](https://myanimelist.net/anime/499)
has no themoviedb_id should be: [44179](https://www.themoviedb.org/movie/44179)

mad_id: [21571](https://myanimelist.net/anime/21571)
is not themoviedb_id: [447404](https://www.themoviedb.org/movie/447404)
the themoviedb_id should be: [332485](https://www.themoviedb.org/movie/332485)

mad_id: [42256](https://myanimelist.net/anime/42256)
is not themoviedb_id: [10052](https://www.themoviedb.org/movie/10052)
I could not find the correct one

mad_id: [34946](https://myanimelist.net/anime/34946)
is not themoviedb_id: [109445](https://www.themoviedb.org/movie/109445)
I could not find the correct one

mad_id: [16620](https://myanimelist.net/anime/16620)
is not themoviedb_id: [38582](https://www.themoviedb.org/movie/38582)
the themoviedb_id should be: [536076](https://www.themoviedb.org/movie/536076)

mad_id: [30408](https://myanimelist.net/anime/30408)
is not themoviedb_id: [39469](https://www.themoviedb.org/movie/39469)
I could not find the correct one

mad_id: [578](https://myanimelist.net/anime/578)
is not themoviedb_id: [76826](https://www.themoviedb.org/movie/76826)
the themoviedb_id should be: [12477](https://www.themoviedb.org/movie/12477)

mad_id: [17233](https://myanimelist.net/anime/17233)
is not themoviedb_id: [345914](https://www.themoviedb.org/movie/345914)
the themoviedb_id should be: [134569](https://www.themoviedb.org/movie/134569)

mad_id: [2047](https://myanimelist.net/anime/2047)
is not themoviedb_id: [10144](https://www.themoviedb.org/movie/10144)
the themoviedb_id should be: [85797](https://www.themoviedb.org/movie/85797)

mad_id: [18617](https://myanimelist.net/anime/18617)
is not themoviedb_id: [10625](https://www.themoviedb.org/movie/10625)
the themoviedb_id should be: [357405](https://www.themoviedb.org/movie/357405)

mad_id: [31348](https://myanimelist.net/anime/31348)
is not themoviedb_id: [10160](https://www.themoviedb.org/movie/10160)
I could not find the correct one

mad_id: [743](https://myanimelist.net/anime/743)
has no themoviedb_id should be: [21057](https://www.themoviedb.org/movie/21057)

mad_id: [1943](https://myanimelist.net/anime/1943)
is not themoviedb_id: [50270](https://www.themoviedb.org/movie/50270)
the themoviedb_id should be: [4977](https://www.themoviedb.org/movie/4977)

mad_id: [4026](https://myanimelist.net/anime/4026)
is not themoviedb_id: [25961](https://www.themoviedb.org/movie/25961)
the themoviedb_id should be: [47292](https://www.themoviedb.org/movie/47292)

mad_id: [37966](https://myanimelist.net/anime/37966)
has no themoviedb_id should be: [571891](https://www.themoviedb.org/movie/571891)

mad_id: [5421](https://myanimelist.net/anime/5421)
is not themoviedb_id: [85](https://www.themoviedb.org/movie/85)
the themoviedb_id should be: [35715](https://www.themoviedb.org/movie/35715)

mad_id: [34417](https://myanimelist.net/anime/34417)
is not themoviedb_id: [221732](https://www.themoviedb.org/movie/221732)
I could not find the correct one

mad_id: [30334](https://myanimelist.net/anime/30334)
is not themoviedb_id: [2668](https://www.themoviedb.org/movie/2668)
the themoviedb_id should be: [525115](https://www.themoviedb.org/movie/525115)

mad_id: [30341](https://myanimelist.net/anime/30341)
is not themoviedb_id: [37135](https://www.themoviedb.org/movie/37135)
the themoviedb_id should be: [469162](https://www.themoviedb.org/movie/469162)

mad_id: [3755](https://myanimelist.net/anime/3755)
is not themoviedb_id: [28032](https://www.themoviedb.org/movie/28032)
the themoviedb_id should be: [86646](https://www.themoviedb.org/movie/86646)

mad_id: [24573](https://myanimelist.net/anime/24573)
is not themoviedb_id: [60293](https://www.themoviedb.org/movie/60293)
the themoviedb_id should be: [724630](https://www.themoviedb.org/movie/724630) (I think im a little unsure about this one)

mad_id: [7876](https://myanimelist.net/anime/7876)
is not themoviedb_id: [630](https://www.themoviedb.org/movie/630)
the themoviedb_id should be: [66081](https://www.themoviedb.org/movie/66081)

mad_id: [31262](https://myanimelist.net/anime/31262)
is not themoviedb_id: [251](https://www.themoviedb.org/movie/251)
the themoviedb_id should be: [258570](https://www.themoviedb.org/movie/258570)

mad_id: [30268](https://myanimelist.net/anime/30268)
is not themoviedb_id: [1911](https://www.themoviedb.org/movie/1911)
I could not find the correct one

mad_id: [5931](https://myanimelist.net/anime/5931)
is not thetvdb_id: [208791](https://thetvdb.com/?tab=series&id=208791)
the thetvdb_id should be removed
I could not find the correct one

mad_id: [41823](https://myanimelist.net/anime/41823) does not exists
mad_id: [41823](https://myanimelist.net/anime/41823) does not exists

mad_id: [5613](https://myanimelist.net/anime/5613)
is not thetvdb_id: [82046](https://thetvdb.com/?tab=series&id=82046)
the thetvdb_id should be removed
I could not find the correct one

mad_id: [25541](https://myanimelist.net/anime/25541)
is not themoviedb_id: [60735](https://www.themoviedb.org/movie/60735)
the themoviedb_id should be: [767743](https://www.themoviedb.org/movie/767743)

mad_id: [35691](https://myanimelist.net/anime/35691)
is not themoviedb_id: [64432](https://www.themoviedb.org/movie/64432)
the themoviedb_id should be: [767743](https://www.themoviedb.org/movie/767743)

mad_id: [5241](https://myanimelist.net/anime/5241)
is not thetvdb_id: [82046](https://thetvdb.com/?tab=series&id=82046)
the thetvdb_id should be removed
I could not find the correct one

mad_id: [18039](https://myanimelist.net/anime/18039)
is not thetvdb_id: [73741](https://thetvdb.com/?tab=series&id=73741)
the thetvdb_id should be removed
I could not find the correct one

mad_id: [2263](https://myanimelist.net/anime/2263)
is not thetvdb_id: [73629](https://thetvdb.com/?tab=series&id=73629)
the thetvdb_id should be removed
I could not find the correct one

mad_id: [41751](https://myanimelist.net/anime/41751)
is not themoviedb_id: [80344](https://www.themoviedb.org/movie/80344)
I could not find the correct one

mad_id: [6919](https://myanimelist.net/anime/6919)
is not thetvdb_id: [71168](https://thetvdb.com/?tab=series&id=71168)
the thetvdb_id should be: [236061](https://thetvdb.com/?tab=series&id=236061)

mad_id: [93](https://myanimelist.net/anime/93)
is not thetvdb_id: [74474](https://thetvdb.com/?tab=series&id=74474)
the thetvdb_id should be: [254931](https://thetvdb.com/?tab=series&id=254931)

mad_id: [32379](https://myanimelist.net/anime/32379)
is not thetvdb_id: [73752](https://thetvdb.com/?tab=series&id=73752)
the thetvdb_id should be: [307111](https://thetvdb.com/?tab=series&id=307111)

mad_id: [34055](https://myanimelist.net/anime/34055)
is not thetvdb_id: [73752](https://thetvdb.com/?tab=series&id=73752)
the thetvdb_id should be: [307111](https://thetvdb.com/?tab=series&id=307111)

mad_id: [1132](https://myanimelist.net/anime/1132)
is not thetvdb_id: [347328](https://thetvdb.com/?tab=series&id=347328)
the thetvdb_id should be: [380653](https://thetvdb.com/?tab=series&id=380653)

mad_id: [40192](https://myanimelist.net/anime/40192)
the thetvdb_id should be: [369139](https://thetvdb.com/?tab=series&id=369139)

mad_id: [31821](https://myanimelist.net/anime/31821)
the thetvdb_id should be: [291630](https://thetvdb.com/?tab=series&id=291630)

mad_id: [28249](https://myanimelist.net/anime/28249)
is not thetvdb_id: [125781](https://thetvdb.com/?tab=series&id=125781)
the thetvdb_id should be: [291630](https://thetvdb.com/?tab=series&id=291630)

mad_id: [11061](https://myanimelist.net/anime/11061)
is not thetvdb_id: [79076](https://thetvdb.com/?tab=series&id=79076)
the thetvdb_id should be: [252322](https://thetvdb.com/?tab=series&id=252322)

mad_id: [3270](https://myanimelist.net/anime/3270)
the thetvdb_id should be: [80391](https://thetvdb.com/?tab=series&id=80391)

mad_id: [1410](https://myanimelist.net/anime/1410)
the thetvdb_id should be: [80391](https://thetvdb.com/?tab=series&id=80391)

mad_id: [34389](https://myanimelist.net/anime/34389)
the thetvdb_id should be: [321496](https://thetvdb.com/?tab=series&id=321496)

mad_id: [35224](https://myanimelist.net/anime/35224)
the thetvdb_id should be: [327718](https://thetvdb.com/?tab=series&id=327718)

mad_id: [37521](https://myanimelist.net/anime/37521)
is not thetvdb_id: [344749](https://thetvdb.com/?tab=series&id=344749)
the thetvdb_id should be: [359274](https://thetvdb.com/?tab=series&id=359274)

mad_id: [763](https://myanimelist.net/anime/763)
is not thetvdb_id: [77907](https://thetvdb.com/?tab=series&id=77907)
the thetvdb_id should be: [73315](https://thetvdb.com/?tab=series&id=73315)

**Comment by Fribb** [comment]
> mal_id: 24573

I removed themoviedb_id because it didn't seem to match that well, the title on MAL didn't fit the title on themoviedb (can't read Japanese though)

> mal_id: 7876

it actually wasn't themoviedb_id 66081 but rather [222960](https://www.themoviedb.org/movie/222960-the-wizard-of-oz)

> mad_id: [35691](https://myanimelist.net/anime/35691) is not themoviedb_id: [64432](https://www.themoviedb.org/movie/64432) the themoviedb_id should be: [767743](https://www.themoviedb.org/movie/767743)

did you write that wrong because 767743 was the same as the `mad_id: [25541](https://myanimelist.net/anime/25541)`, the mapping to [64432](https://www.themoviedb.org/movie/64432-animen-triton-force) seems correct though

> mal_id: [2263](https://myanimelist.net/anime/2263)

change that to [themoviedb_id 78422](https://www.themoviedb.org/tv/78422)

**Comment by meisnate12** [comment]
> > mal_id: 7876
> 
> it actually wasn't themoviedb_id 66081 but rather [222960](https://www.themoviedb.org/movie/222960-the-wizard-of-oz)

Yea that was a mistype

> 
> > mad_id: [35691](https://myanimelist.net/anime/35691) is not themoviedb_id: [64432](https://www.themoviedb.org/movie/64432) the themoviedb_id should be: [767743](https://www.themoviedb.org/movie/767743)
> 
> did you write that wrong because 767743 was the same as the `mad_id: [25541](https://myanimelist.net/anime/25541)`, the mapping to [64432](https://www.themoviedb.org/movie/64432-animen-triton-force) seems correct though

Yea i messed that one up too mad_id: [25541](https://myanimelist.net/anime/25541) should have themoviedb_id: [767743](https://www.themoviedb.org/movie/767743)


> > mal_id: [2263](https://myanimelist.net/anime/2263)
> 
> change that to [themoviedb_id 78422](https://www.themoviedb.org/tv/78422)

themoviedb will use the same numbers as a tv vs a movie and i couldn't find it on thetvdb. It could cause problems if you have themoviedb TV IDs mixed with their movie ids 

For Example this id [themoviedb_id 78422](https://www.themoviedb.org/movie/78422) leads to a different movie. I don't know how the list was intended but i thought if it has a moviedb ID then its a movie and if it has a tvdbid then its a show

**Comment by Fribb** [comment]
> themoviedb will use the same numbers as a tv vs a movie and i couldn't find it on thetvdb. It could cause problems if you have themoviedb TV IDs mixed with their movie ids

that is interesting but shouldn't be a problem because you request the IDs differently in the themoviedb API.

for example, if you want to get a movie then you would access the `/movie/{movie_id}` endpoint. With a TV-Show this would be the `/tv/{tv_id}` endpoint. It would be confusing requesting an ID of a TV-Show on the Movie endpoint though, that I would agree on but MyAnimeList does offer the Media Type with (at least) TV and Movie.

**Comment by meisnate12** [comment]
yea my biggest problem and how i ended up finding most of these issues is because im trying to find the mal ID using tmdb IDs for movies and tvdb IDs for shows so if i was trying to find the show listed above mine would fail since it looks for the tvdb ID when searching for a show. either way ill make my app work regardless just wanted to know what the intention is behind it all

**Comment by Fribb** [comment]
The project sprang into life because of another Project I have, the Plex metadata Agent for MyAnimeList. MyAnimeList isn't providing a lot or any additional images for backgrounds, few or only one poster and no banners or anything like that. TheTVDB and TheMovieDB do.

I could just use the search endpoints to look up the title on the APIs but I had some concerns with that. The first concern was that if I search for it then I would reinvent the wheel because there were already Agents that do this, I would only need to allow that they provide the metadata as well. The other concern was that it would be out of my hand in regards to the matches. An incorrect or too similar name would result in a wrong match which then would download wrong metadata. Depending on the "state" of the Agents it could work one time but not the other.

So I thought that it would be a good way to have some sort of mapping between MyAnimeList and the other platforms.

It basically should be a way simpler version of the anime-list project [here](https://github.com/ScudLee/anime-lists) for anidb.net and in JSON instead of XML.

So far, even the creation of the lists is a bit too rudimentary because what basically happens is that I get all the titles from MyAnimeList and search for each and every one of them on the respective platform and select the one ID that got found the most. That is very prone to error but worked probably for most cases.

I still have to dig into that project, the generator, again and have to rewrite it because of the changes to thetvdb APIv4 which is now paid and to use it for my Agent I would have to provide both theTVDB and theMovieDB IDs for those users who have a thetvdb APIv4 key or rather want to use themoviedb instead...
